# **Veri Bilimi Atölyesi-7**

Sayılardan oluşan bir boyutlu array oluşturulur. Arrayi oluştururken sayıların veri tipini integer olarak belirtilir. Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakılır.

In [1]:
import numpy as np

In [4]:
array1 = np.array([1,2,3,4], dtype= int )

In [5]:
np.ndim(array1)

1

In [6]:
np.size(array1)

4

İki ve üç boyutlu arrayler oluşturulur. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşılır. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır.

İki boyutlu array: [[1,2,6,7], [4,3,9,5]]

Üç boyutlu array: [[[7,5,14],[21,8,11]], [[8,6,20],[14,3,9]]]

In [7]:
array2 = np.array([[1,2,6,7],[4,3,9,5]])

array3 = np.array([[[7,5,14],[21,8,11]],[[8,6,20],[14,3,9]]])

In [8]:
array2.ndim

2

In [9]:
array3.ndim

3

In [14]:
array2.size

8

In [15]:
array3.size

12

In [16]:
array2.shape

(2, 4)

In [17]:
array3.shape

(2, 2, 3)

In [23]:
array2[1,3]

5

In [27]:
array3[0,1,2]

11

In [18]:
array2[:, 1:3]

array([[2, 6],
       [3, 9]])

In [21]:
array3[0, 1:, :]

array([[21,  8, 11]])

Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturulur. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır

In [28]:
bir_boyutlu = np.array([1, 2, 3, 4, 5])

iki_boyutlu = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])

uc_boyutlu = np.array([[[1, 2, 3],
                        [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]],
                       [[13, 14, 15],
                        [16, 17, 18]]])

In [29]:
bir_boyutlu[0]

1

In [30]:
bir_boyutlu[:2]

array([1, 2])

In [32]:
iki_boyutlu[2,1]

8

In [33]:
iki_boyutlu[:, 0]

array([1, 4, 7])

In [34]:
uc_boyutlu[0, 1, 2]

6

In [35]:
uc_boyutlu[0, :2]

array([[1, 2, 3],
       [4, 5, 6]])

Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturulur. Bu arrayler satır ve sütun bazında birleştirilir.

In [36]:
sifir_matris = np.zeros((3, 3))

In [37]:
bir_matris = np.ones((3, 3))

In [38]:
birlesik_matris_satir = np.concatenate((sifir_matris, bir_matris), axis=0)

In [39]:
birlesik_matris_satir

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
birlesik_matris_sutun = np.concatenate((sifir_matris, bir_matris), axis=1)

In [41]:
birlesik_matris_sutun

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])